import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const text=readFileSync('docs/protocol.md','utf8');
const source=ts.createSourceFile('game/types.ts',readFileSync('packages/contracts/src/game/types.ts','utf8'),ts.ScriptTarget.Latest,true);
const aliases=new Map(source.statements.filter(ts.isTypeAliasDeclaration).map(x=>[x.name.text,x]));
const base=aliases.get('BaseGame').getText(source);
assert.ok(!/\bsubmit\s*:/.test(base));
assert.ok(!aliases.has('GameUpdate'));
assert.ok(/\bbind\s*:/.test(base)&&/\brun\s*:/.test(base));
const runtime=readFileSync('packages/contracts/src/runtime/types.ts','utf8');
assert.ok(runtime.includes('Promise<GameOutcome<GameHandle<G, Q>>>'));
assert.ok(!/\binitial\s*:|\bGameUpdate\b/.test(runtime));
assert.ok(!/\bsubmit\b|\bGameUpdate\b/.test(text));
assert.ok(text.includes('BaseGame 的唯一推进入口是 run'));
console.log('PASS F2 removed: one BaseGame driving API, direct binder result, callback-only event delivery.');
assert.ok(!/\bcapture\??:|\breadRecords\??:|\binstance\??:/.test(base));
for(const premise of ['旧句柄及其别名的操作返回 instance_owned','BaseGameBinder 只持有新句柄，不向外暴露它'])assert.ok(text.includes(premise));
console.log('OPEN F1: capture access after transfer is still not closed; protocol freeze remains pending.');
console.log('SCOPE declaration regression checks, not production execution evidence.');
