import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const read=path=>readFileSync(path,'utf8');
const aliases=path=>new Map(ts.createSourceFile(path,read(path),ts.ScriptTarget.Latest,true).statements.filter(ts.isTypeAliasDeclaration).map(x=>[x.name.text,x.getText()]));
const game=aliases('packages/contracts/src/game/types.ts');
const core=aliases('packages/contracts/src/core/types.ts');
const author=aliases('packages/contracts/src/authoring/types.ts');
assert.ok(!/\bsubmit\s*:/.test(game.get('BaseGame')));
assert.ok(!/\bresume\s*:/.test(core.get('Instance')));
assert.ok(!game.has('GameUpdate'));
for(const declaration of [game.get('BaseGame'),core.get('Instance')]){
  assert.ok(/\bbind\s*:/.test(declaration)&&/\brun\s*:/.test(declaration));
}
assert.ok(read('packages/contracts/src/runtime/types.ts').includes('Promise<GameOutcome<GameHandle<G, Q>>>'));
for(const name of ['DecisionData','TerminalData'])assert.ok(!/\bevents\s*:/.test(author.get(name)));
assert.ok(/kind: 'event';[\s\S]*events:/.test(author.get('GamePorts')));
assert.ok(/read: \(instanceId: InstanceId, input: RecordRead\)/.test(core.get('InstanceCapture')));
assert.ok(/release: \(instanceId: InstanceId\)/.test(core.get('InstanceCapture')));
assert.ok(read('tests/contracts/basegame-types.ts').includes('core.capture.read(base.id'));
assert.ok(read('tests/contracts/instance-types.ts').includes('capture.release(instance.id)'));
const protocol=read('docs/protocol.md');
assert.ok(!/\bsubmit\b|\bGameUpdate\b|\bresume\b/.test(protocol));
for(const premise of ['close 释放执行现场但保留捕捉记录','transfer 只移动执行控制权','decision.receive 和 finish 不产生事件'])assert.ok(protocol.includes(premise),premise);
console.log('PASS: Instance and BaseGame each have one driving entrypoint.');
console.log('PASS: only event ports deliver notifications; terminal state has no pending delivery.');
console.log('PASS: capture is provider-scoped by identity and survives control transfer/close until release.');
console.log('SCOPE declaration and consumer checks; implementation conformance remains a separate obligation.');
const runtime=aliases('packages/contracts/src/runtime/types.ts');
for(const name of ['NativeCoreLoader','ControlledCoreLoader'])assert.ok(runtime.get(name).includes('Promise<Outcome<LoadedCore<S, P, R>>>'));
const fields=declaration=>{
  const sf=ts.createSourceFile('check.ts',declaration,ts.ScriptTarget.Latest,true);
  const type=sf.statements[0].type;
  const literal=ts.isIntersectionTypeNode(type)?type.types.find(ts.isTypeLiteralNode):type;
  return literal.members.map(x=>x.name?.getText(sf)).sort();
};
assert.deepEqual(fields(core.get('Instance')),['bind','close','fork','id','inspect','run','transfer']);
assert.deepEqual(fields(game.get('BaseGame')),['bind','close','describe','fork','id','inspect','observe','query','run','save','validate']);
assert.deepEqual(fields(core.get('InstanceCapture')),['read','release']);
console.log('PASS: exact method inventories and both loader failure outcomes match the freeze proof.');
