import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import ts from 'typescript';
const read=p=>readFileSync(p,'utf8');
const aliases=path=>new Map(ts.createSourceFile(path,read(path),ts.ScriptTarget.Latest,true).statements.filter(ts.isTypeAliasDeclaration).map(x=>[x.name.text,x.getText()]));
const base='packages/contracts/src/';
const game=aliases(base+'game/types.ts'),instance=aliases(base+'instance/types.ts'),author=aliases(base+'authoring/types.ts');
const fields=declaration=>{const sf=ts.createSourceFile('x.ts',declaration,ts.ScriptTarget.Latest,true);const type=sf.statements[0].type;const literal=ts.isIntersectionTypeNode(type)?type.types.find(ts.isTypeLiteralNode):type;return literal.members.map(x=>x.name?.getText(sf)).sort();};
assert.deepEqual(fields(instance.get('Instance')),['bind','close','fork','id','inspect','run','transfer']);
assert.deepEqual(fields(game.get('BaseGame')),['bind','close','describe','id','inspect','observe','run','validate']);
assert.deepEqual(fields(instance.get('InstanceRunStop')),['accepted','pause','state']);
assert.ok(game.get('BaseGame').includes('accepted:Accepted<T,P,C>|null'));
assert.ok(game.get('Accepted').includes("kind:'action'")&&game.get('Accepted').includes("kind:'control'"));
assert.ok(author.get('RequestData').includes("player:G['player']"));
assert.ok(game.get('GameBindings').includes('onRequest?'));
assert.ok(author.get('GameContract').includes('session?:'));
assert.ok(!game.get('BaseGame').includes('bindControl'));
assert.ok(!game.get('BaseGame').includes('fork'));
const root=read(base+'index.ts');
const rootSource=ts.createSourceFile('index.ts',root,ts.ScriptTarget.Latest,true);
const names=rootSource.statements.flatMap(x=>ts.isExportDeclaration(x)&&x.exportClause&&ts.isNamedExports(x.exportClause)?x.exportClause.elements.map(e=>e.name.text):[]);
assert.deepEqual(names.sort(),['BaseGame','Core','GameModule','GameSDK','IO','InputOptions','Instance','Program','ProgramModule','Request'].sort());
const files=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(dir+'/'+e.name):e.name.endsWith('.ts')?[dir+'/'+e.name]:[]);
const removed=/\b(?:observer|observerFor|playerFor|signalPlayers|acceptsSignal|onDecision|acceptedInputs|acceptedReplies|maxInputs|maxReplies|DecisionOffer|GameRequest|GameInput|ChoiceInput|DecisionId|GameRunStop|InstanceRunLimits|GameRunLimits|StateTransition|StateConstruction|FactExtraction|DecisionPolicy)\b/;
for(const path of [...files(base),...files('games/doudizhu/src'),'README.md','docs/architecture.md','docs/protocol.md','docs/doudizhu.md','docs/requirements.md'])assert.ok(!removed.test(read(path)),`${path}: old surface remains`);
const pkg=JSON.parse(read('packages/contracts/package.json'));
assert.deepEqual(Object.keys(pkg.exports).sort(),['.','./core','./instance','./game','./authoring','./session','./persistence','./branching','./capture','./loading'].sort());
assert.ok(!read(base+'core/types.ts').includes("../game/"));
assert.ok(!read(base+'instance/types.ts').includes("../game/"));
for(const path of [base+'core/types.ts',base+'instance/types.ts',base+'game/types.ts'])assert.ok(!/\.\.\/(persistence|capture|branching|session|loading)\//.test(read(path)),`${path}: basic depends on optional feature`);
for(const statement of ['一次最多接受一个游戏输入','动作不包含通用交付时间','accepted 表示这次实际提交','调用方负责提供匹配的程序与 contract'])assert.ok(read('docs/protocol.md').includes(statement),statement);
console.log('PASS: ten default entrypoints; functional subpaths expose optional capabilities independently.');
console.log('PASS: direct player requests and pure actions; separate optional session callback.');
console.log('PASS: one-step Instance/Game run and concrete accepted input survive stop states.');
console.log('PASS: current public source and active specifications contain no removed interfaces.');
console.log('PASS: Core/Instance are game-neutral; basic modules do not import optional features.');
