import assert from 'node:assert/strict';
import { z } from 'zod';
import type { GameInputDefinitions, GameSchemas } from '../../../packages/contracts/src/index.ts';
const input=z.number().int().transform(n=>n+1);
const schemas={setup:z.null(),state:z.null(),event:z.null(),result:z.number(),interactions:{move:{request:z.null(),input,context:z.null(),description:z.never()}}};
type G={setup:null;state:null;event:null;result:number;interactions:{move:{request:null;input:z.infer<typeof input>;context:null;description:never}}};
const accepted:GameSchemas<G>=schemas;
const inputs:GameInputDefinitions<G>={move:{options:z.strictObject({kind:z.literal('exact'),values:z.array(z.number())}),describe:()=>({kind:'exact',values:[1]}),validate:({input})=>input===1?{valid:true}:{valid:false,reason:'only_one'}}};
const raw=0;
const validated=accepted.interactions.move.input.parse(raw);
assert.equal(inputs.move.validate({state:null,request:null,input:validated}).valid,true);
const parsedAgain=accepted.interactions.move.input.parse(validated);
assert.equal(validated,1);assert.equal(parsedAgain,2);
assert.equal(inputs.move.validate({state:null,request:null,input:parsedAgain}).valid,false);
console.log(JSON.stringify({raw,validated,parsedAgain,property:'parse(parse(x)) != parse(x)'}));
console.log('PROVED: public schema types admit non-idempotent normalization. This fixture is not a production runtime trace.');
